-- phpMyAdmin SQL Dump
-- version phpStudy 2014
-- http://www.phpmyadmin.net
--
-- 主机: localhost
-- 生成日期: 2020 �?01 �?10 �?07:57
-- 服务器版本: 5.5.53
-- PHP 版本: 5.6.27

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- 数据库: `XXX`
--

-- --------------------------------------------------------

--
-- 表的结构 `message`
--

CREATE TABLE IF NOT EXISTS `message` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL DEFAULT '',
  `miaoshu` varchar(1000) NOT NULL DEFAULT '',
  `level` varchar(99) NOT NULL,
  `fenxi` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `jianyi` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10003 ;

--
-- 转存表中的数据 `message`
--

INSERT INTO `message` (`id`, `name`, `miaoshu`, `level`, `fenxi`, `url`, `jianyi`) VALUES
(1, '.svn信息泄漏', '\r站点使用svn做生产环境版本控制，但是.svn目录没有做访问权限控制，可以通过.svn/entries来遍历文件和目录列表。\r\r', '\r1\r', '\r可能泄露一些敏感信息：SVN库的路径，有权限修改文件或者目录的用户，修改历史，甚至站点目录结构等。\r', '', '\r删除SVN相关目录或者限制对SVN相关目录的访问。\r'),
(2, 'Apache AXIS不存在的Java Web Service路径泄露', '\r在应用程序测试过程中，检测到所测试的中间件因为版本过低导致路径泄漏问题。\r\r', '\r2\r', '\r应用程序的绝对路径信息泄漏，可能导致攻击者收集到该应用程序的大量敏感信息，进而寻找利用方法进行进一步的侵入。\r', '', '\r更新补丁或升级更高的版本。\r'),
(3, 'Apache HTTP Server畸形Range和Range-Request选项处理远程拒绝服务漏洞', '\rApache HTTP Server在处理Range和Range-Request头选项中包含的大量重叠范围指定命令时存在的问题，攻击者可通过发送到服务器的特制HTTP请求耗尽系统资源，导致Apache失去响应，甚至造成操作系统资源耗尽。\r', '\r2\r', '\rApache HTTP Server在处理Range和Range-Request选项生成回应时存在漏洞，远程攻击者可能利用此漏洞通过发送恶意请求导致服务器失去响应，导致拒绝服务。\r', '', '\r目前厂商已经发布了升级补丁以修复这个安全问题，请到厂商的主页下载：www.apache.org\r临时解决办法：\r1、 使用SetEnvIf配置命令来忽略畸形的Ranger选项，适用于Apache 2.0和2.2 。\r    修改Apache的配置文件httpd.conf。\r    去掉如下行的注释：\r    LoadModule headers_module modules/mod_headers.so\r    增加如下行的配置命令：\r    SetEnvIf Range (,.*?){5,} bad-range=1\r    RequestHeader unset Range env=bad-range\r    重启Apache服务器。\r2、 安装启用mod_rewrite，设置规则过滤规则禁止带有畸形的Ranger选项的请求，适用于所有版本的\r  Apache\r    修改Apache的配置文件httpd.conf。\r    去掉如下行的注释：\r    LoadModule rewrite_module modules/mod_rewrite.so\r    加入如下的mod_rewrite的规则配置行：\r    RewriteEngine on\r    RewriteCond %{HTTP:range} !(^bytes=[^,]+(,[^,]+){0,4}$|^$)\r    RewriteRule .* - [F]\r    重启Apache服务器。\r'),
(4, 'Apache HttpOnly Cookie泄露', '\r测试发现，系统采用Apache作为web服务器，但是Apache HTTP Server 2.2.x多个版本没有正确严格限制HTTP请求头信息，请求头信息超过LimitRequestFieldSize长度时服务器返回400（Bad Request）错误，并在返回信息中将出错请求头内容爆出。 \r\r', '\r3\r', '\r攻击者可以利用该漏洞获取完整的httponly cookies，相当于可以帮助攻击者突破COOKIE中的HTTPONLY属性限制，会造成身份盗用等安全问题。\r', '', '\r更新apache到最新稳定版。\r    Apache官方提供4种错误处理方式        （http://httpd.apache.org/docs/2.0/mod/core.html#errordocument），如下\r    1.    output asimple hardcoded error message输出一个简单生硬的错误代码信息\r    2.    output acustomized message输出一段信息\r    3.    redirect to alocal URL-path to handle the problem/error转向一个本地的自定义页面 \r    4.   redirect to an external URL to handle theproblem/error转向一个外部URL\r经测试，对于400错误只有方法2有效，返回包不会再包含cookie内容\r'),
(5, 'Apache Struts错误消息跨站漏洞', '\r当前Web应用程序使用的Apache Struts源代码框架的默认错误消息存在XSS跨站漏洞，当攻击者请求不存在的资源时，该请求会直接被插入到Apache Struts的错误消息中，没有进行过滤。因此，攻击者可以构造特殊的访问请求，实现XSS跨站攻击。\r\r', '\r1\r', '\r攻击者可以通过构造URL注入JavaScript、VBScript、ActiveX、HTML或者Flash的手段，利用跨站脚本漏洞欺骗用户，收集Cookie等相关数据并冒充其他用户。通过精心构造的恶意代码，可以让访问者访问非法网站或下载恶意木马，如果再结合其他攻击手段（如社会工程学、提权等），甚至可以获取系统的管理权限。\r', '', '\r升级Apache Struts的版本。\r用户可参考如下厂商提供的安全补丁以修复该漏洞： https://struts.apache.org/struts1eol-announcement.html\r'),
(6, 'Apache Tomcat样例目录session操纵漏洞', '\rApache Tomcat默认安装包含”/examples”目录，里面存着众多的样例，其中session样例(/examples/servlets/servlet/SessionExample)允许用户对session进行操纵, 因为session是全局通用的，所以用户可以通过操纵session获取管理员权限。\r/\r', '\r2\r', '\r攻击者很有可能通过操作session获取系统管理权限。\r', '', '\r删除此文件。\r'),
(7, 'Apache Tomcat管理后台地址泄漏', '\r在应用程序测试过程中，检测到所测试的应用系统存在Apache Tomcat管理后台地址泄漏风险。\r\r', '\r2\r', '\rApache Tomcat管理后台是用来管理中间件的，对于web应用本身来说并不需要，并且通过Apache Tomcat管理后台攻击者甚至可以直接上传war格式的木马获得服务器权限。\r', '', '\r删除tomcat安装目录下webapps下的manager目录。\r'),
(8, 'Apache多视图缺省扩展名漏洞', '\rApache有一个称为“多重视图”的功能组件，缺省情况下，通常都会在特定目录上打开这个功能部件（有时是整个配置都打开这个功能部件）。“多重视图”的功能是：如果访问者不知道服务器上某个文件的文件扩展名，则可以不提供文件扩展名来请求文件，只提供访问者支持的 MIME 类型（例如：Accept: text/html）。Apache便会根据MIME类型为访问者提供含有适当扩展名的文件。\r但如果攻击者访问一个文件时不提供扩展名，并且同时提交一个错误的MIME类型到服务器，则Apache会返回服务器上存在的以该“文件名”为名字的所有扩展名的文件列表。\r\r', '\r2\r', '\r应用程序所在WebServer的配置不正确，导致应用程序目录结构泄漏，攻击者可以在得到这些敏感信息之后执行更进一步的攻击。\r', '', '\r修改Apache配置文件，禁用“多重视图”选项。\r禁用方法：\r删除httpd.conf或其他配置文件中Options区块的“MultiViews”值。\r'),
(9, 'Apache版本过低', '\rApache版本过低，存在多个高危漏洞。\r\r', '\r1\r', '\rApache版本过低，存在多个高危漏洞，攻击者可利用这些漏洞对主机发起攻击，比如通过DOS攻击漏洞导致Apache拒绝服务。\r', '', '\r升级Apache到最新稳定版。\r'),
(10, 'ASP.NET版本信息泄漏', '\r应用系统未屏蔽ASP.NET版本信息，导致信息泄漏。\r/\r', '\r3\r', '\r敏感信息的暴露会提供给攻击者更多的可用信息，引起更多被侵入的风险。\r', '', '\r修改web.config中的配置：\r<System.Web>\r <httpRuntime enableVersionHeader="false" />\r</System.Web>\r'),
(11, 'ASP.NET错误回显未屏蔽导致绝对路径泄露', '\rASP.NET很容易受到路径泄露的攻击。原因是当服务器启用了默认错误提示时，攻击者可以通过不当使用 "~" 字符的方式获得站点的绝对路径，从而进一步攻击站点。\r/\r', '\r2\r', '\r攻击者可以通过不当使用 "~" 字符的方式获得站点的绝对路径，这可能会帮助攻击者开展进一步攻击和获取有关Web应用程序文件系统结构的信息。\r', '', '\r关闭ASP.NET默认错误回显。\r'),
(12, 'BEA WebLogic管理后台地址泄漏', '\rBEA WebLogic 管理界面未删除或未设置可访问权限。\r\r', '\r2\r', '\r攻击者可能利用BEA WebLogic 管理界面实现更改站点配置、权限提升、控制服务器等攻击。\r', '', '\r限制访问管理控制台，倘若不需要，请将其除去。\r'),
(13, 'clientaccesspolicy.xml允许跨域资源访问', '\r当前ClientAccessPolicy.xml配置允许Silverlights从任何其他域访问当前域上的所有资源。\r\r', '\r2\r', '\r攻击者可利用此漏洞进行跨域请求伪造。\r', '', '\r限定ClientAccessPolicy.xml中domain uri的域名范围，限定resource path的路径范围。\r'),
(14, 'crossdomain.xml配置允许跨域资源访问', '\r当前crossdomain.xml配置允许Silverlights和Flash从任何其他域访问当前域上的所有资源。\r\r', '\r2\r', '\r攻击者可利用此漏洞进行跨域请求伪造。\r', '', '\r对于不需要外部加载资源的网站，crossdomain.xml中更改allow-access-from的domain属性为域名白名单。\r修复大致样本参考如下（备注：示例中的app10000.qzoneapp.com,app10000.imgcache.qzoneapp.com请修改为自己指定的站点）：\r<?xml version="1.0"?>\r<cross-domain-policy>\r<allow-access-from secure="false" domain="*.qq.com"/>\r<allow-access-from secure="false" domain="*.soso.com"/>\r<allow-access-from secure="false" domain="*.paipai.com"/>\r<allow-access-from secure="false" domain="*.gtimg.cn"/>\r<allow-access-from secure="false" domain="*.pengyou.com"/>\r<allow-access-from secure="false" domain="app10000.qzoneapp.com"/>\r<allow-access-from secure="false" domain="app10000.imgcache.qzoneapp.com"/>\r</cross-domain-policy>\r'),
(15, 'CSRF跨站请求伪造', '\r攻击者通过伪造来自受信任用户的请求，达到增加、删除、篡改网站内容的目的。\r\r', '\r2\r', '\r攻击者冒充用户/管理员，伪造请求，进行篡改、转帐、改密码、发邮件等非法操作。\r', '', '\r验证HTTP Referer字段。\r请求地址中添加token并验证（token不放在cookie中，放在http请求参数中，服务端对其进行验证）\r将token加入http头属性中，避免了token出现在浏览器中，被泄露。\r'),
(16, 'CVS信息泄漏', '\r站点使用CVS做生产环境版本控制，但是CVS相关目录没有做访问权限控制，攻击者可以通过CVS相关目录来获取敏感信息。\r\r', '\r1\r', '\r可能泄露一些敏感信息：CVS库的路径，有权限修改文件或者目录的用户，修改历史，甚至站点目录结构等。\r', '', '\r在目标服务器上删除CVS相关目录或者限制对CVS相关目录的访问。\r'),
(17, 'Dojo XSS跨站漏洞', '\rDojo 1.1及之前之前版本中的dijit.Editor存在XSS跨站漏洞，攻击者可以借助TEXTAREA元素中的XML实体，注入任意的web脚本或HTML到页面中。\r\r', '\r1\r', '\r攻击者可以通过构造URL注入JavaScript、VBScript、ActiveX、HTML或者Flash的手段，利用跨站脚本漏洞欺骗用户，收集Cookie等相关数据并冒充其他用户。通过精心构造的恶意代码，可以让访问者访问非法网站或下载恶意木马，如果再结合其他攻击手段（如社会工程学、提权等），甚至可以获取系统的管理权限。\r', '', '\r升级Dojo至1.2或1.2以上版本。\r如果无法升级，建议对用户输入的数据进行全面安全检查或过滤，尤其注意检查是否包含HTML特殊字符。这些检查或过滤必须在服务器端完成，建议过滤的常见危险字符如下：\r|（竖线符号）\r& （& 符号）\r;（分号）\r$（美元符号）\r%（百分比符号）\r@（at 符号）\r''（单引号）\r"（引号）\r\\''（反斜杠转义单引号）\r\\"（反斜杠转义引号）\r<>（尖括号）\r()（括号）\r+（加号）\rCR（回车符，ASCII 0x0d）\rLF（换行，ASCII 0x0a）\r,（逗号）\r\\（反斜杠）\r'),
(18, 'eWebEditor编辑器后台地址泄漏', '\r站点使用了ewebeditor编辑器，编辑器的后台对于网站的普通管理并没有用，而编辑器后台很容易导致网站被恶意攻击者轻易利用。\r\r', '\r1\r', '\r攻击者可以利用ewebeditor编辑器的后台上传webshell控制网站，甚至通过权限提升控制服务器。\r', '', '\r删除ewebeditor编辑器的后台或者限制对ewebeditor编辑器的后台的访问。\r'),
(19, 'FckEditor编辑器危险页面未删除', '\r应用系统使用了FckEditor编辑器，但没有删除危险页面，这些页面可以很容易的被恶意攻击者利用。\r\r', '\r2\r', '\r攻击者可以轻易利用这些危险页面，这可能导致网站被植入木马，甚至可能导致服务器被控制。\r', '', '\r根据业务需求：\r如果这些页面可以被删除，则直接删除。\r如果这些页面不可被删除，则修改FckEditor的目录名，防止攻击者通过目录猜解的方式访问FckEditor编辑器的这些危险页面。\r'),
(20, 'FckEditor编辑器版本过低', '\r站点使用了FckEditor编辑器，编辑器的版本过低。\r\r', '\r1\r', '\r低版本的FckEditor编辑器存在大量高危漏洞，攻击者可以轻易利用这些漏洞，这可能导致网站被植入木马，甚至可能导致服务器被控制。\r', '', '\r升级FckEditor编辑器的版本。\r'),
(21, 'Flash参数AllowScriptAccess值为不安全的always', '\r应用程序中Flash设定的AllowScriptAccess 参数可确定已加载的SWF（或任何后续加载的SWF）是否有权访问这些SWF所嵌入的Web页面。如果参数设为“always”，那么从任何域中装入的SWF都可能将脚本注入到当前Web页面中。\r\r', '\r3\r', '\r应用系统没有对Flash的权限做出限制，这会产生网络钓鱼、用户会话信息搜集等风险。\r', '', '\r请将 AllowScriptAccess参数设为“sameDomain”，告诉Flash播放器，只有从父SWF的相同域中装入的SWF文件有对当前Web页面的脚本访问权。\r'),
(22, 'FortiGate设备认证绕过漏洞预警报告', 'FortiGate设备被披露存在认证绕过漏洞，攻击者可通过该漏洞直接获取目标设备控制权限', '1', 'FortiGate设备被披露存在认证绕过漏洞，攻击者可通过该漏洞直接获取目标设备控制权限，操控设备启停、流量窃听、甚至开启VPN进行内网渗透等，危害巨大。由于FortiGate网络设备在我公司网络中使用广泛，建议尽快排查并修复。', '', ''),
(23, 'handlebars XSS漏洞', '\r程序当前引用的handlebars.js版本较低，只对<>进行了转义，并没有考虑其他危险字符串的转义，可导致XSS跨站漏洞。\r\r漏洞官方修复介绍：https://github.com/wycats/handlebars.js/pull/68\r', '\r1\r', '\r攻击者可以通过构造URL注入JavaScript、VBScript、ActiveX、HTML或者Flash的手段，利用跨站脚本漏洞欺骗用户，收集Cookie等相关数据并冒充其他用户。通过精心构造的恶意代码，可以让访问者访问非法网站或下载恶意木马，如果再结合其他攻击手段（如社会工程学、提权等），甚至可以获取系统的管理权限。\r', '', '\r升级handlebars.js到最新稳定版，官网下载地址：\rhttp://handlebarsjs.com/installation.html\r'),
(24, 'htaccess文件内容可读', '\rWeb server配置存在逻辑缺陷，导致.htaccess文件内容可读。\r\r', '\r1\r', '\r攻击者可以通过.htaccess的文件内容了解应用系统的伪静态URL重写规则，进而可以发现更多的安全缺陷使应用系统处于更严峻的安全环境下。\r', '', '\r修改.htaccess规则内容，禁止对.htaccess和.htpasswd文件的直接访问。\r在.htaccess文件中添加以下内容：\r<Files .htaccess>\rorder allow,deny\rdeny from all\r</Files>\r'),
(25, 'HTML5 CORS跨域资源共享权限设置不严格', '\r应用系统使用了HTML5技术，启用了对CORS跨域资源共享技术的支持，但Access-Control-Allow-Origin属性被设定为*，允许任意域访问应用系统的资源。\r/\r', '\r3\r', '\r攻击者可以利用此特性，结合XSS跨站等前端漏洞完成劫持用户会话、窃取防CSRF随机token、访问内网服务资源等攻击。\r', '', '\r修改中间件配置和程序源代码，配置Access-Control-Allow-Origin属性为合适的可信域，禁止设置为*。\r'),
(26, 'HTML注释敏感信息泄漏', '\r测试人员发现，网站的HTML注释中，存在系统配置相关的敏感信息，这可能导致敏感信息泄漏。\r/\r', '\r2\r', '\r有时开发者会忘记从生产环境中除去某些安装、调试或测试注释信息。这些注释信息有可能包括 Web 用户所不应访问的敏感信息。攻击者可能从这些注释中获得敏感信息以进行进一步的攻击。\r', '', '\r不可将敏感的注释信息遗留在正式发布的HTML页面上，未来要避免出现这个情况，确保服务器上没有非正常操作所必备的注释信息。\r'),
(27, 'HTTP Response Splitting漏洞', '\rHTTP Response Splitting漏洞是属于CRLF Injection的一种，因为程序没有对%0d%0a换行符进行过滤，导致攻击者可以控制HTTP header，产生HTTP Response Splitting漏洞。\r\r', '\r1\r', '\r通过对HTTP Response Splitting漏洞的利用，攻击者可以控制用户的HTTP Response Header，这会导致用户会话劫持、用户敏感信息泄漏等高危风险。\r', '', '\r过滤或者替换用户请求中的%0d%0a，过滤输入数据正文中的“\\r\\n”等换行符。\r'),
(28, 'http.sys远程代码执行', '\r远程执行代码漏洞存在于 HTTP 协议堆栈 (HTTP.sys) 中，当 HTTP.sys 未正确分析经特殊设计的 HTTP 请求时会导致此漏洞。\r\r', '\r1\r', '\r当服务器收到攻击者构造的恶意HTTP请求时，可触发远程代码在目标系统以系统权限执行，或直接导致服务器蓝屏。\r', '', '\r及时升级微软官方安全补丁， 微软已于北京时间4月15日发布漏洞补丁包，用户可通过Windows update获取补丁包并及时进行升级。微软发布的漏洞公告：http://technet.microsoft.com/security/bulletin/MS15-034\r'),
(29, 'HTTP主机头攻击', '\r为了方便的获得网站域名，开发人员一般依赖于HTTP Host header。但是这个header是不可信赖的，如果应用程序没有对host header值进行处理，就有可能造成恶意代码的传入。\r\r', '\r3\r', '\r攻击者可以任意伪造X-Forwarded-Host字段的值，以使应用程序执行任意JS/HTML脚本，攻击者可以很方便的实现网络钓鱼、XSS跨站、挂马等攻击。\r', '', '\rweb应用程序应该使用SERVER_NAME而不是host header。\r在Apache和Nginx里可以通过设置一个虚拟机来记录所有的非法host header。在Nginx里还可以通过指定一个SERVER_NAME名单，Apache也可以通过指定一个SERVER_NAME名单并开启UseCanonicalName选项。\r'),
(30, 'HTTP参数污染', '\r应用系统没有对HTTP参数的重复赋值进行识别和处理，导致存在HTTP参数污染漏洞。\r污染前：\r/\r污染后：\r/\r', '\r2\r', '\r攻击者可以利用HTTP参数污染漏洞影响程序正常运行逻辑，或绕过WAF拦截继续进行攻击。\r', '', '\r修改应用系统源代码，识别并判断HTTP参数的重复赋值，进而进行不同情况的处理，建议识别出重复赋值时直接中断请求。\r'),
(31, 'IBM HTTP Server控制面板地址泄漏', '\r在应用程序测试过程中，检测到所测试的应用系统存在IBM HTTP Server管理后台地址泄漏风险。\r\r', '\r2\r', '\rIBM HTTP Server控制面板是用来管理webserver的，对于web应用本身来说并不需要，并且攻击者可能通过IBM HTTP Server控制面板获得更为有利的入侵条件。\r', '', '\r删除/隐藏IBM HTTP Server控制面板，或限制控制面板的访问权。\r'),
(32, 'IBM WebSphere Application Server 文件泄露', '\r在应用程序测试过程中，检测到所测试的应用系统中间件未及时更新补丁，存在应用程序源代码泄漏风险。\r\r', '\r1\r', '\r中间件补丁更新不及时，攻击者可以通过发送构造好的畸形数据包对应用程序的所有源代码进行遍历。\r', '', '\r及时更新中间件安全补丁。\r'),
(33, 'IBM WebSphere snoopservlet敏感信息泄漏', '\rIBM WebSphere snoopservlet存在敏感信息泄漏漏洞，测试发现中间件默认安装完毕之后没有删除这些默认页面，导致信息泄漏。\r\r', '\r2\r', '\r可能会泄漏 Web 服务器安装的绝对路径、服务器的主机名等信息，这可能会帮助攻击者开展进一步的攻击。\r', '', '\r如果不需要，删除这些默认页面。\r如果确实需要，请为这些默认页面设置严格的访问权限。\r'),
(34, 'IIS短文件名漏洞', '\r为了兼容16位MS-DOS程序，Windows为文件名较长的文件（和文件夹）生成了对应的windows 8.3 短文件名，而生成的短文件名符合一定的规律，可以被暴力猜解。\r/\r', '\r1\r', '\r由于应用程序中间件补丁更新不及时，导致存在IIS短文件名漏洞，这可能导致敏感信息泄漏，也可能被攻击者用于进行下一步攻击的信息搜集。\r', '', '\r1）通用有效方法：\r禁用windows系统中的短文件名功能。\r打开注册表并打开此目录        HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\FileSystem\r修改 NtfsDisable8dot3NameCreation 的值为1 。\r修改完成后，需要重启系统生效。\r2）简单有效方法：CMD命令\rWindows Server 2008 R2\r查询是否开启短文件名功能：fsutil 8dot3name query\r关闭该功能：fsutil 8dot3name set 1\rWindows Server 2003\r关闭该功能：fsutil behavior set disable8dot3 1\r3）手动验证\r新建文件夹并创建几个文件，打开CMD进入该文件夹呢执行dir /x 检测，看不到有显示短文件名则成功。\r'),
(35, 'Java Servlet源代码泄露', '\r在应用程序测试过程中，检测到所测试的应用系统框架版本较低，存在应用程序源代码泄漏风险。\r\r', '\r1\r', '\r系统框架版本较低，攻击者可以通过发送构造好的畸形数据包对应用程序的所有源代码进行遍历。\r', '', '\r升级应用程序框架。\r'),
(36, 'Java反序列漏洞', '\r由于某些java容器（中间件）中的jar包存在反序列化漏洞，导致可被远程命令执行。影响容器有：jenkins，jboss，weblogic，websphere等。\r\r', '\r1\r', '\r利用反序列漏洞可上传jsp Webshell文件，获取服务器完全控制权限，并且可以执行任意命令。\r', '', '\r1.JBOSS\rJBoss服务专有用户权限，没有登录权限，达到权限最小化,启用防火墙,防护防火墙策略设置，限定可以连接到JBoss的IP,安全验证配置,若是公开服务，需要在jmx-invoker-service.xml中开启权限验证,更新源代码,在JBoss源代码中打入最新的官方patch。\r2.Weblogic\r首先停止weblogic，在中间件modules目录下找到名为\rcom.bea.core.apache.commons.collections_x.x.x.jar文件\r然后下载最新的commons-collections(bin包)，用压缩包中的commons-collections-x.x.x.jar替换有漏洞的jar包\rjar包下载地址：\rhttp://commons.apache.org/proper/commons-collections/download_collections.cgi\r注意：保持原jar包的名字，即名字不变换掉jar包\r最后启动weblogic。\r'),
(37, 'JBoss服务器敏感信息泄漏', '\rJBoss控制台未设置访问限制策略，导致任意用户都可以直接看到服务器的敏感信息。\r\r', '\r1\r', '\rJBoss控制台未设置访问限制策略，导致任意用户都可以直接看到服务器的敏感信息，恶意攻击者可以通过控制台显示的敏感信息进而进一步攻击站点。\r', '', '\r配置JBoss控制台，增加访问控制策略。\r'),
(38, 'JetBrains .idea文件泄漏', '\r应用系统的生产环境中存在开发者开发过程中使用的.idea文件。\r\r', '\r2\r', '\r攻击者可从.idea文件中获得程序的逻辑结构、开发过程中的绝对路径等信息。\r', '', '\r若不需要，则删除受影响文件。若确实需要，则为此类文件设置访问规则，禁止通过WEB直接访问。\r以Apache配置为例，在. htaccess或http.conf中配置访问规则：\r<Directory ~ "\\.idea">\rOrder allow,deny\rDeny from all\r</Directory>\r'),
(39, 'jQuery XSS漏洞', '\r1.x系列版本等于或低于1.12的jQuery，和2.x系列版本等于或低于2.2的jQuery，过滤用户输入数据所使用的正则表达式存在缺陷，可能导致LOCATION.HASH跨站漏洞。\r/\r漏洞官方修复介绍：http://bugs.jquery.com/ticket/9521\r', '\r3\r', '\r攻击者可插入任意HTML/JavaScript代码到页面中，可获取用户会话cookie、用户访问URL、用户浏览器及操作系统版本等信息，可插入伪造的登录页面进行钓鱼，可利用浏览器漏洞进行挂马。\r', '', '\r临时解决方案：\r暂时隐藏jQuery版本信息，避免被攻击者识别出版本号；\r为应用系统制定统一的、影响全局的危险字符黑名单，发现输入中存在危险字符时直接返回固定的错误页面。\r正式解决方案：\r等待jQuery发布新的修复版本后升级。\r'),
(40, 'jquery-migrate XSS跨站漏洞', '\r1.1版本的jQuery-migrate对$(location.hash)和$(#<tag>)处理不当，导致XSS漏洞。\r\r', '\r1\r', '\r攻击者可以通过构造URL注入JavaScript、VBScript、ActiveX、HTML或者Flash的手段，利用跨站脚本漏洞欺骗用户，收集Cookie等相关数据并冒充其他用户。通过精心构造的恶意代码，可以让访问者访问非法网站或下载恶意木马，如果再结合其他攻击手段（如社会工程学、提权等），甚至可以获取系统的管理权限。\r', '', '\r升级jquery-ui至1.10.0或1.10.0以上。\r'),
(41, 'jquery-ui-dialog XSS跨站漏洞', '\r版本在1.8.0和1.10.0之间的jQuery.ui.dialog的标题选项在写入DOM时没有被正确地转义，导致XSS漏洞。\r\r', '\r1\r', '\r攻击者可以通过构造URL注入JavaScript、VBScript、ActiveX、HTML或者Flash的手段，利用跨站脚本漏洞欺骗用户，收集Cookie等相关数据并冒充其他用户。通过精心构造的恶意代码，可以让访问者访问非法网站或下载恶意木马，如果再结合其他攻击手段（如社会工程学、提权等），甚至可以获取系统的管理权限。\r', '', '\r升级jquery-ui至1.10.0或1.10.0以上。\r'),
(42, 'Microsoft IIS 缺少 Host 头信息泄露', '\rWeb 服务器或应用程序服务器是以不安全的方式配置的，当发送不含“Host”头的请求时，在特定配置下，Microsoft IIS 会泄露它在“Location”头中的内部 IP 地址。\r\r', '\r2\r', '\r攻击者可以利用这个问题来获取关于服务器机器/内网的敏感信息，从而进一步攻击站点。\r', '', '\r根据 Microsoft 安全文章 Q218180 来应用配置更改：\rhttp://support.microsoft.com/default.aspx?scid=KB;EN-US;Q218180\r'),
(43, 'Microsoft IIS“Translate f”源代码泄露', '\r在应用程序测试过程中，检测到所测试的应用系统中间件配置不当，存在应用程序源代码泄漏风险。\r\r', '\r1\r', '\r中间件配置不当，攻击者可以通过发送构造好的畸形数据包对应用程序的所有源代码进行遍历。\r', '', '\r请检查站点配置中的“访问脚本源文件”复选框。\r'),
(44, 'OpenSSL SSL3.0加密协议信息泄露漏洞', '\rOpenSSL 1.0.1i及之前版本中使用的SSL protocol 3.0版本中存在安全漏洞，该漏洞源于程序使用非确定性的CBC填充。\rCVE编号：CVE-2014-3566\r漏洞介绍：https://www.openssl.org/news/vulnerabilities.html\r\r', '\r3\r', '\r攻击者可借助padding-oracle攻击利用该漏洞实施中间人攻击，获取明文数据。\r', '', '\r升级OpenSSL到最新稳定版。\r临时解决方法：\r 如果您不能立刻安装补丁或者升级，NSFOCUS建议您采取以下措施以降低威胁：\r* 禁用SSL 3.0协议。\r 目前常用浏览器只有IE 6.0仍然不支持TLS 1.0，禁用SSL 3.0协议将影响IE 6客户的\rSSL访问。\r 服务端禁用方法：\rApache 2.x:\r在mod_ssl配置文件中使用如下命令禁用SSLv2和SSLv3：\rSSLProtocol All -SSLv2 -SSLv3\r重启Apache\r Nginx:\r在配置文件中使用：\rssl_protocols TLSv1 TLSv1.1 TLSv1.2;\r重启Nginx\r IIS:\r查找如下注册表项：\rHKey_Local_Machine\\System\\CurrentControlSet\\Control\\SecurityProviders \\SCHANNEL\\Protocols\r该注册表项通常包含以下子项：\r* PCT 1.0\r * SSL 2.0\r * SSL 3.0\r * TLS 1.0\r每个注册表项都保留适用于该项的协议相关信息。可以在服务器上禁用这些协议中的任一种。为此，\r 请在协议SSL 3.0的服务器子项中创建一个新的DWORD值。将DWORD值设置为“00 00 00 00”。\r'),
(45, 'OpenSSL心脏滴血漏洞', '\r由于未能在memcpy()调用受害用户输入内容作为长度参数之前正确进行边界检查。攻击者可以追踪OpenSSL所分配的64KB缓存、将超出必要范围的字节信息复制到缓存当中再返回缓存内容，这样一来受害者的内存内容就会以每次64KB的速度进行泄露。\r请求包中的数据实际长度远远小于其标明的length长度，Server端根据其标明的length长度分配了堆，然后尝试将请求包中的数据都拷贝过来形成回应包，于是便从内存中的请求包数据处开始复制了length个长度的字节，已经远远超过了数据的实际长度，从而造成数据的泄露。通过这种方式，一般可以得到SSL使用的Server端的私钥，从而获得SSL会话密钥，以及用户的账号等信息，最多64KB的数据。\r\r', '\r1\r', '\r攻击者可利用该漏洞循环读取主机服务器内存中的敏感信息(如用户名、密码、Cookie、私钥等)。\r', '', '\r（1）升级openssl软件。要解决此漏洞，建议服务器管理员或使用1.0.1g版，或使用-DOPENSSL_NO_HEARTBEATS选项重新编译OpenSSL，从而禁用易受攻击的功能，直至可以更新服务器软件。（OpenSSL官方）最新版本升级地址为：https://www.openssl.org/source/.\r（2）重新编译OpenSSL并去掉DOPENSSL_NO_HEARTBEATS扩展。\r$ echo -e "B\\n" | openssl s_client -connect targetwebsite:443 -tlsextdebug 2>&1| grep ''heartbeart''\r（3）如果不能升级OpenSSL可以更新IPTable防火墙规则。t# Log rules\riptables -t filter -A INPUT  -p tcp --dport 443  -m u32 --u32 \\\r"52=0x18030000:0x1803FFFF" -j LOG --log-prefix "BLOCKED: HEARTBEAT"\r# Block rules\riptables -t filter -A INPUT  -p tcp --dport 443  -m u32 --u32 \\ "52=0x18030000:0x1803FFFF" -j DROP\r'),
(46, 'phpinfo() XSS跨站漏洞', '\r因PHP未及时更更新补丁，导致版本V4.4.2和5.1.2的PHP phpinfo()函数存在跨站漏洞。\r\r', '\r1\r', '\r攻击者可以通过构造URL注入JavaScript、VBScript、ActiveX、HTML或者Flash的手段，利用跨站脚本漏洞欺骗用户，收集Cookie等相关数据并冒充其他用户。通过精心构造的恶意代码，可以让访问者访问非法网站或下载恶意木马，如果再结合其他攻击手段（如社会工程学、提权等），甚至可以获取系统的管理权限。\r', '', '\r升级PHP版本，更新PHP安全补丁。\r'),
(47, 'phpinfo信息泄漏', '\r系统中存在phpinfo页面，泄漏了大量配置信息。\r/\r', '\r2\r', '\r攻击者可通过phpinfo页面获得主机操作系统类型、主机名、绝对路径、PHP配置开关、数据库类型等大量敏感信息。\r', '', '\r若不需要此文件，删除此phpinfo文件。若确实需要此文件，限制此文件的访问权。\r'),
(48, 'Prototype JavaScript Framework跨站Ajax请求漏洞', '\r应用系统使用的Prototype JavaScript Framework存在Prototype JavaScript Framework跨站Ajax请求漏洞。\r\r', '\r1\r', '\rPrototype JavaScript Framework 1.6.0.2之前的版本中存在一个未明错误，攻击者可以利用此漏洞实施ajax跨站请求攻击。\r', '', '\r升级Prototype JavaScript Framework到最新稳定版。\r'),
(49, 'RC4密码套件检测', '\r允许攻击者恢复有限数量的明文从TLS连接时使用RC4加密。攻击产生的RC4算法变得明显在TLS时相同的明文密文加密的密钥流生成重复统计缺陷。\r/\r', '\r2\r', '\r攻击者可以恢复少量的明文从TLS连接时使用RC4加密。\r', '', '\r最有效的对抗这种攻击是停止使用RC4 TLS。咨询网站的参考资料，以了解更多关于这一攻击的信息，以及如何保护它。\r对于NGINX的修补:\r修改nginx配置文件中的 ssl_ciphers项\r ssl_ciphers"ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";\rssl_prefer_server_ciphers on;\r重新加载：\r$sudo /etc/init.d/nginx reload\r对于apache的修复:\r打开配置文件\r$ sudo vi /etc/httpd/conf.d/ssl.conf\r修改配置\rSSLCipherSuite\rHIGH:MEDIUM:!aNULL:!MD5;!RC4\r$ sudo /etc/init.d/httpd restart\r对于TOMCAT的修复:\rserver.xml 中SSL connector加入以下内容:\rSSLEnabled="true"sslEnabledProtocols="TLSv1,TLSv1.1,TLSv1.2"ciphers="TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_2'),
(50, 'Redis未授权访问', '\rRedis数据库没有设置密码，攻击者可以任意连接。\r/\r/\r', '\r1\r', '\r攻击者可以任意连接Redis数据库，可获取数据库中所有信息，造成严重的信息泄露。在知道WEB绝对路径的情况下可以写入webshell，结合当前最新的漏洞，攻击者可以成功将自己的公钥写入服务器的/root/.ssh文件夹的authotrized_keys文件中，进而可以直接登录目标服务器。\r', '', '\r配置bind选项, 限定可以连接Redis服务器的IP，并修改redis的默认端口6379；\r配置AUTH，设置密码，密码会以明文方式保存在redis配置文件中；\r配置rename-command CONFIG "RENAME_CONFIG"，这样即使存在未授权访问，也能够给攻击者使用config指令加大难度。\r'),
(51, 'Slow Http Denial of Service Attack', '\r针对任意HTTP Server，建立一个连接，以很低的速度发包，并保持住这个连接不断开。如果客户端持续建立这样的连接，那么服务器上可用的连接池将很快被占满，从而导致拒绝服务攻击。\r\r', '\r2\r', '\rSlowloris和Slow HTTP POST拒绝服务攻击基于HTTP协议，由于应用设计要求服务器完全接收请求后才处理，如果一个HTTP请求是不完整的，或者传输率是非常低的，服务器将保持其资源忙并等待其余的数据。如果服务器一直等待，会导致服务器资源耗尽，造成拒绝服务。\r', '', '\r缓解方法:\r  通过server.xml内定义的连接器的connectionTimeout属性，配置一个合适的超时时间。\rhttps://www.cnblogs.com/redcoatjk/p/3926525.html\r'),
(52, 'SQL注入漏洞', '\r程序过滤不严，存在SQL注入漏洞。\r\r', '\r1\r', '\r攻击者可直接控制数据库，数据库中存储的所有信息都将泄漏。若数据库的权限较高，攻击者可以直接写入恶意文件到服务器上，甚至可以直接执行操作系统命令，直接控制主机服务器。\r', '', '\r采用sql语句预编译和绑定变量，是防御sql注入的最佳方法。\r在客户端和服务端对程序接收到的数据进行全面过滤，建议过滤的常见危险字符如下：\r;\r''\r"\r()\r,\r\\\rand\ror\runion\rselect\rwhere\rlimit\rgroup\rby\rhex\rsubstr\r'),
(53, 'SQL盲注漏洞', '\r在应用程序测试过程中，检测到所测试的 Web 应用程序不具备敏感字符过滤功能，进而导致SQL注入的产生。\r\r', '\r1\r', '\r在应用程序测试过程中，检测到所测试的 Web 应用程序不具备敏感字符过滤功能，进而导致SQL注入的产生。攻击者可以通过构造特殊URL的手段，利用SQL注入漏洞从数据库中获取敏感数据、修改数据库数据（插入/更新/删除） 、执行数据库管理操作（如关闭数据库管理系统）、恢复存在于数据库文件系统中的指定文件内容，在某些情况下能执行操作系统命令。\r', '', '\r    采用sql语句预编译和绑定变量，是防御sql注入的最佳方法\r对用户输入的数据进行全面安全检查或过滤，尤其注意检查是否包含HTML特殊字符。这些检查或过滤必须在服务器端完成，建议过滤的常见危险字符如下：\r;\r''\r"\r<>\r()\r,\r\\\rscript\rsvg\ralert\rconfirm\rprompt\ronload\ronmouseover\ronfocus\ronerror\rxss\r'),
(54, 'SSL证书公钥小于2048位', '\r当前SSL证书的公钥长度小于2048位。\r\r', '\r2\r', '\r攻击者更容易攻破SSL证书加密算法。\r', '', '\r升级SSL证书公钥长度为2048位或更大长度。\r'),
(55, 'Struts2 S2-016-S2-017任意代码执行漏洞', '\rApache Struts2的action:、redirect:和redirectAction:前缀参数在实现其功能的过程中使用了Ognl表达式，并将用户通过URL提交的内容拼接入Ognl表达式中，从而造成攻击者可以通过构造恶意URL来执行任意Java代码，进而可执行任意命令。\rredirect:和redirectAction:此两项前缀为Struts默认开启功能，目前Struts 2.3.15.1以下版本均存在此漏洞。\r\r', '\r1\r', '\r攻击者利用Struts2任意代码执行漏洞，可以直接在服务器上执行任意命令，写入webshell，添加SSH用户，控制服务器。\r', '', '\r目前Apache Struts2已经在2.3.15.1中修补了这一漏洞，请尽快升级Struts框架版本。\r'),
(56, 'Struts2 S2-032任意代码执行漏洞', '\r启用了动态方法调用模式的Apache Struts2存在漏洞，攻击者可以通过构造恶意URL来执行任意Java代码，进而可执行任意命令。\r\rCVE编号：CVE-2016-3081\r官方公告：http://struts.apache.org/docs/s2-032.html\r', '\r1\r', '\r攻击者利用Struts2任意代码执行漏洞，可以直接在服务器上执行任意命令，写入webshell，添加SSH用户，控制服务器。\r', '', '\r1、关闭动态方法调用：\r<constantname=“struts.enable.DynamicMethodInvocation” value=“false”/>\r2、升级Struts2版本至2.3.20.2或2.3.24.2或2.3.28.1。\r'),
(57, 'Struts2 S2-045任意代码执行漏洞', '\rApache Struts 2被曝存在远程命令执行漏洞，漏洞编号为S2-045，CVE编号CVE-2017-5638，在使用基于Jakarta插件的文件上传功能时可能存在远程命令执行，导致系统被入侵，漏洞评级为高危。\r漏洞关键点：\r基于Jakarta（Jakarta Multipart parser）插件的文件上传功能恶意攻击者精心构造Content-Type的值。\r/\r/\r/\r', '\r1\r', '\r漏洞风险：攻击者通过利用漏洞可以实现远程命令执行\r影响版本：Struts 2.3.5-Struts 2.3.31、Struts 2.5-Struts 2.5.10\r安全版本：Struts 2.3.32、Struts 2.5.10.1\r', '', '\r如您正在使用Jakarta文件上传插件或者是存在漏洞的Struts 2版本请升级至Struts2安全版本，使用Servlet过滤器验证Content-Type过滤不匹配的请求multipart/form-data。\r'),
(58, 'Struts2 S2-046任意代码执行漏洞 -', '\rApache Struts 2被曝存在远程命令执行漏洞，漏洞编号为S2-046，CVE编号CVE-2017-5638，使用Jakarta插件处理文件上传时可能导致远程代码执行（RCE）漏洞。，导致系统被入侵，漏洞评级为高危。\r漏洞关键点：\r上传文件的大小（由Content-Length头指定）大于Struts2允许的最大大小（2GB）。\r文件名内容构造恶意的OGNL内容。\r/\r/\r/\r', '\r1\r', '\r漏洞风险：攻击者通过利用漏洞可以实现远程命令执行\r影响版本：Struts 2.3.5-Struts 2.3.31、Struts 2.5-Struts 2.5.10\r安全版本：Struts 2.3.32、Struts 2.5.10.1\r', '', '\r1、严格过滤 Content-Type 、filename里的内容，严禁ognl表达式相关字段。\r2、 如果您使用基于Jakarta插件，请升级到Apache Struts 2.3.32或2.5.10.1版本。（强烈推荐）\rStruts 2.3.32下载地址： \rhttps://cwiki.apache.org/confluence/display/WW/Version+Notes+2.3.32                 \rStruts 2.5.10.1下载地址：\rhttps ://cwiki.apache.org/confluence/display/WW/Version+Notes+2.5.10.1\r'),
(59, 'Struts2任意代码执行漏洞', '\r在应用程序测试过程中，检测到所测试的应用系统的代码框架为Struts2，该框架在未更新补丁的情况下存在任意代码执行漏洞。\r\r', '\r1\r', '\r攻击者利用Struts2任意代码执行漏洞，可以直接在服务器上执行任意命令，写入webshell，添加SSH用户，控制服务器。\r', '', '\r升级Struts框架。\r'),
(60, 'Struts2开发界面未删除', '\rStruts 2默认的表达式语言是OGNL，OGNL是Object-Graph Navigation Language的缩写，它是一种功能强大的表达式语言（Expression Language，简称为EL），通过它简单一致的表达式语法，可以存取对象的任意属性，调用对象的方法，遍历整个对象的结构图，实现字段类型转化等功能。\r\r', '\r1\r', '\r攻击者可以从此界面获取web应用程序的敏感信息，甚至是核心信息。虽然前台的界面做了return false处理，但是攻击者可以通过分析、修改页面脚本来绕过，获取开发者权限，那么网站将处于巨大的危险之中。\r', '', '\r如果这些页面可以被删除，则直接删除。\r如果这些页面不可被删除，则设置访问权限，进行权限鉴定。\r'),
(61, 'test-cgi敏感信息泄露', '\rtest-cgi目录未删除。\r\r', '\r2\r', '\r攻击者可以查看服务器环境变量。\r', '', '\r删除test-cgi目录。\r'),
(62, 'Tomcat status页面信息泄漏', '\r通过访问status目录，可判断服务器是否存在Tomcat status页面：\r\r', '\r3\r', '\r恶意用户或攻击者通过Tomcat status页面查看到服务器的敏感信息。\r', '', '\r删除Tomcat status页面，或限制Tomcat status页面的访问权限。\r'),
(63, 'Tomcat管理后台弱口令', '\rTomcat默认管理后台/ manager/html存在弱口令，口令：tomcat/tomcat\r    \r', '\r1\r', '\rTomcat存在默认后台，并且密码为默认密码，攻击者可以通过Tomcat 默认管理后台上传war文件包获得webshell，进而进一步控制服务器。\r', '', '\r删除tomcat默认管理后台，如果确实需要，给tomcat默认管理后台设置一个健壮的密码并更改默认后台的目录。\r'),
(64, 'Unicenter TNG服务信息泄漏', '\r企业系统管理软件Unicenter TNG存在安全隐患，攻击者可以通过发送“HELP”命令到远程服务端口获取远程服务信息。\r\r', '\r2\r', '\r攻击者可以通过发送“HELP”命令到远程服务端口获取远程服务信息。\r', '', '\r限定可访问Unicenter TNG监听端口的IP范围，并关注Unicenter TNG官网获取安全补丁。\r'),
(65, 'Unicode编码转换漏洞', '\r低于3.0版本的Unicode字符在转换为UTF-8编码时，超长字节序列和错误格式会引起子序列的安全问题。\r\r', '\r1\r', '\r攻击者可利用此缺陷对恶意字符进行编码转换，进而绕过程序本身或安全设备的安全过滤与拦截，常被用于SQL注入、XSS跨站等漏洞的利用。\r', '', '\r1、 升级Unicode版本至官方最新稳定版本http://www.unicode.org\r2、 无论接收到的字符是什么编码，都直接对这些字符进行危险字符的过滤与拦截，并确认对特殊字符进行安全编码后再输出。\r'),
(66, 'WebLogic Server管理后台地址泄漏', '\r在应用程序测试过程中，检测到所测试的应用系统BEA WebLogic 管理界面未删除或未设置可访问权限。\r\r', '\r2\r', '\rBEA WebLogic管理后台是用来管理中间件的，对于web应用本身来说并不需要，并且通过BEA WebLogic管理后台攻击者甚至可以直接上传木马获得服务器权限。\r', '', '\r限制访问管理控制台，倘若不需要，请将其除去。\r'),
(67, 'WebLogic SetupUDDIExplorer.jsp XSS跨站漏洞', '\r当前版本的WebLogic Server组件中的WLS - Web Services子组件存在安全漏洞，页面SetupUDDIExplorer.jsp存在XSS跨站漏洞。\r\r', '\r1\r', '\r攻击者可以通过构造URL注入JavaScript、VBScript、ActiveX、HTML或者Flash的手段，利用跨站脚本漏洞欺骗用户，收集Cookie等相关数据并冒充其他用户。通过精心构造的恶意代码，可以让访问者访问非法网站或下载恶意木马，如果再结合其他攻击手段（如社会工程学、提权等），甚至可以获取系统的管理权限。\r', '', '\r及时更新安全补丁：\rhttp://www.oracle.com/technetwork/topics/security/cpujul2014-1972956.html\r'),
(68, 'WebLogic SSRF服务端请求伪造', '\r当前版本的WebLogic Server组件中的WLS - Web Services子组件存在安全漏洞。\r\r', '\r1\r', '\r攻击者可利用此漏洞将WebLogic所在主机作为跳板，对WebLogic所在主机能连通和访问的内部网络进行端口扫描、banner发现等攻击。\r', '', '\r及时更新安全补丁：\rhttp://www.oracle.com/technetwork/topics/security/cpujul2014-1972956.html\r1.将weblogic安装目录下的wlserver_10.3/server/lib/uddiexplorer.war做好备份\r2.将weblogic安装目录下的server/lib/uddiexplorer.war下载\r3.用winrar等工具打开uddiexplorer.war\r4.将其下的SearchPublicRegistries.jsp重命名为SearchPublicRegistries.jspx\r5.保存后上传回服务端替换原先的uddiexplorer.war\r6.对于多台主机组成的集群，针对每台主机都要做这样的操作\r7.由于每个server的tmp目录下都有缓存所以修改后要彻底重启weblogic（即停应用--停server--停控制台--启控制台--启server--启应用）\r（验证如果不重启即便删除服务器上能找到的所有SearchPublicRegistries.jsp的缓存页面，页面依然可以访问；重启后确实不能访问页面）\r如果不需要uddi那么也可以直接删除uddiexplorer.war，但要注意在实际操作中发现删除uddiexplorer.war如果没有当即执行重启，那么会数天内uddiexplorer.war会被自动还原。\r'),
(69, 'WebLogic控制面板弱口令', '\r在应用程序测试过程中，检测到所测试的应用系统WebLogic控制面板存在弱口令。\r\r', '\r1\r', '\rWebLogic管理后台是用来管理中间件的，对于web应用本身来说并不需要，并且通过WebLogic管理后台攻击者甚至可以直接上传木马获得服务器权限。\r', '', '\r倘若不需要，请限制Weblogic控制面板的访问权限或将其除去。\r如果一定需要，请为Weblogic控制面板设定一个强壮的密码。\r'),
(70, 'WebServer Expect头XSS跨站漏洞', '\rWebServer版本过低，存在Expect头XSS跨站漏洞。\r\r', '\r1\r', '\r通过精心构造的恶意代码，攻击者可以收集Cookie等相关数据并冒充其他用户，也可以让访问者访问非法网站或下载恶意木马，如果再结合其他攻击手段（如社会工程学、提权等），甚至可以获取系统的管理权限。\r', '', '\r升级WebServer到最新稳定版。\r'),
(71, 'Websphere控制面板空口令', '\r在应用程序测试过程中，检测到所测试的应用系统websphere控制面板存在空口令。\r/\r', '\r1\r', '\rWebsphere管理后台是用来管理中间件的，对于web应用本身来说并不需要，并且通过Websphere管理后台攻击者甚至可以直接上传木马获得服务器权限。\r', '', '\r倘若不需要，请限制Websphere控制面板的访问权限或将其除去。\r如果一定需要，请为Websphere控制面板设定一个强壮的密码。\r'),
(72, 'WebSphere配置文件读取漏洞', '\r当前版本的WebSphere版本较低，存在漏洞。\r\r', '\r1\r', '\r攻击者可绕过WebSphere的目录保护，读取应用系统配置文件。\r', '', '\r补丁获取地址：\rhttp://www-01.ibm.com/support/docview.wss?uid=swg24022456\r'),
(73, 'XFS跨框架页面劫持', '\r程序没有验证框架来源页的地址，导致产生XFS跨框架页面劫持漏洞。\r\r', '\r1\r', '\r攻击者可以利用XFS漏洞，通过精心构造的恶意代码，可以让访问者访问非法网站或下载恶意木马，如果再结合其他攻击手段（如社会工程学、提权等），甚至可以获取系统的管理权限。\r', '', '\r对框架页面来源地址进行检查，这些检查或过滤必须在服务器端完成。\r'),
(74, 'xheditor版本较低', '\r应用系统使用了xheditor编辑器，但当前xheditor的版本较低，存在upload.php畸形文件上传、存储型XSS跨站等多个高危漏洞。\r\r', '\r2\r', '\r攻击者可以在调用编辑器的页面插入XSS跨站代码实现钓鱼、挂马等恶意目的，如果webserver是IIS 6.0，攻击者甚至可以直接上传畸形文件获得webshell控制网站及服务器。\r', '', '\r升级到最新稳定版，官网已经发布了漏洞补丁和最新版本。\r漏洞补丁：http://xheditor.com/bug1\r最新版本：http://xheditor.com/changelog\r'),
(75, 'XML外部实体注入', '\r应用系统的XML设置允许引用外部实体（entity），攻击者可构造恶意请求，对应用系统发起攻击。\r\r', '\r1\r', '\r攻击者通过构造恶意内容，可进行读取任意文件、执行系统命令、探测内网端口、攻击内网网站等攻击。\r', '', '\r1、使用开发语言提供的禁用外部实体的方法。\rJAVA：\rDocumentBuilderFactory dbf =DocumentBuilderFactory.newInstance();\rdbf.setExpandEntityReferences(false);\rPHP：\rlibxml_disable_entity_loader(true);\rPython：\rfrom lxml import etree\rxmlData = etree.parse(xmlSource,etree.XMLParser(resolve_entities=False))\r2、过滤用户提交的XML数据，常见可被过滤字符串有：\r<!DOCTYPE\r<!ENTITY\rSYSTEM\rPUBLIC\r');
INSERT INTO `message` (`id`, `name`, `miaoshu`, `level`, `fenxi`, `url`, `jianyi`) VALUES
(76, 'xml配置文件信息泄漏', '\r中间件配置不当，攻击者可直接访问WEB-INF目录下的XML配置文件，获得敏感信息。\r\r', '\r1\r', '\r攻击者可获得配置文件中的绝对路径、数据库连接字符串等敏感信息。\r', '', '\r修改中间件配置，禁止直接访问WEB-INF下的任何文件。\r'),
(77, 'XSS跨站漏洞', '\r程序过滤不严，存在XSS跨站漏洞。\r/\r', '\r1\r', '\r攻击者可插入任意HTML/JavaScript代码到页面中，可获取用户会话cookie、用户访问URL、用户浏览器及操作系统版本等信息，可插入伪造的登录页面进行钓鱼，可利用浏览器漏洞进行挂马。\r', '', '\r设置httponly\r    httponly无法完全的防御xss漏洞，它只是规定了不能使用js去获取cookie的内容，因此它只能防御利用xss进行cookie劫持的问题。Httponly是在set-cookie时标记的，可对单独某个参数标记也可对全部参数标记。由于设置httponly的方法比较简单，使用也很灵活，并且对防御cookie劫持非常有用，因此已经渐渐成为一种默认的标准。\rxss filter\r   Xss filter往往是一个文本文件，里面包含了允许被用户输入提交的字符（也有些是包含不允许用户提交的字符）。它检测的点在于用户输入的时候，xss filter分为白名单与黑名单，推荐使用白名单，但即使使用白名单还是无法完全杜绝xss问题，并且使用不当可能会带来很高的误报率。\r编码转义\r    编码方式有很多，比如html编码、url编码、16进制编码、javascript编码等。\r在处理用户输入时，除了用xss filter的方式过滤一些敏感字符外，还需要配合编码，将一些敏感字符通过编码的方式改变原来的样子，从而不能被浏览器当成js代码执行。\r处理富文本\r   有些网页编辑器允许用户提交一些自定义的html代码，称之为”富文本”。想要在富文本处防御xss漏洞，最简单有效的方式就是控制用户能使用的标签，限制为只能使用a、div等安全的标签。\r处理所有输出类型的xss漏洞\rxss漏洞本质上是一种html注入，也就是将html代码注入到网页中。那么其防御的根本就是在将用户提交的代码显示到页面上时做好一系列的过滤与转义。\r在客户端和服务端对程序接收到的数据进行全面过滤，建议过滤的常见危险字符如下：\r;\r''\r"\r<>\r()\r,\r\\\rscript\rsvg\ralert\rconfirm\rprompt\ronload\ronmouseover\ronfocus\ronerror\rxss\r'),
(78, '上传漏洞-可绕过的可选文件类型限制', '\r系统的文件上传模块只在本地限制了可选文件的类型限制，导致攻击者可轻易绕过此限制，上传可被解析的webshell脚本木马。\r\r', '\r1\r', '\r系统的文件上传模块只在本地客户端限制了用户上传的文件类型，这是不可靠的，攻击者可以直接上传webshell对网站及服务器进行非法操作。\r', '', '\r1. 对上传文件格式进行严格校验及安全扫描，防止上传恶意脚本文件；\r2. 设置权限限制，禁止上传目录的执行权限；\r3. 严格限制可上传的文件类型；\r4. 严格限制上传的文件路径。\r5. 文件扩展名服务端白名单校验。\r6. 文件内容服务端校验。\r7. 上传文件重命名。\r8. 隐藏上传文件路径。\r'),
(79, '上传漏洞-可绕过的本地验证', '\r系统在客户端使用js对用户的上传文件类型进行控制，但是并没有在服务端进行二次验证，导致存在上传漏洞。\r\r', '\r1\r', '\r攻击者可以很轻易的绕过客户端js验证进行非法操作，甚至可能直接控制网站及服务器。\r', '', '\r在客户端进行JS验证的同时，在服务端进行二次验证。\r'),
(80, '上传漏洞', '\r应用系统的上传模块没有任何安全防护措施，导致攻击者可以上传任意文件到服务器以获得webshell。\r\r', '\r1\r', '\r应用系统没有验证上传文件的合法性，导致攻击者可以上传恶意文件到服务器，达到获得webshell控制应用系统甚至控制服务器的目的。\r', '', '\r在前端限制可上传的文件类型。\r在后端验证上传文件的合法性。\r限制上传目录的可执行权限。\r'),
(81, '不安全的单因素认证方式', '\r系统并没有使用双因素强认证方式来实现用户登录。\r\r', '\r3\r', '\r系统并没有使用双因素强认证方式进行用户认证，攻击者在获得应用系统账户密码之后即可冒充合法用户登陆，通过利用这个弱点提升在系统中的访问权限，从而严重的影响系统的完整性、可靠性。\r', '', '\r应用系统登录页面可采用双因素强认证方式。可用的的高强度双因素认证措施包括“帐号静态密码+短信动态密码”、 “帐号静态密码+动态令牌”、“账号静态密码+数字证书“等。\r'),
(82, '不应具备记住我功能', '\r程序具备记住我功能，容易被攻击者利用。\r\r', '\r3\r', '\r若可以接触到用户的浏览器，则攻击者可以利用记住我功能轻易获得用户的用户名信息，甚至可以通过记住密码功能直接登录用户系统，以正常用户的身份执行恶意操作。\r', '', '\r删除记住我功能。\r'),
(83, '不应将认证信息直接写入前端页面', '\r测试人员发现应用系统将认证信息直接写入了前端页面，这是不安全的。\r\r', '\r2\r', '\r攻击者可以通过前端页面上的示例用户名和密码构造特定的字典对应用系统发起攻击，如果前端页面上显示的认证信息是正确的，攻击者甚至可以直接登录应用系统。\r', '', '\r不要将认证信息写入前端页面代码中。\r'),
(84, '不正确的POST方法', '\r应用系统传递敏感数据使用了POST方法，但敏感数据是在URL中传递的，不是在POST方法的DATA部分传递的。\r/\r', '\r2\r', '\r攻击者可通过document.URI等属性获得敏感数据的内容。\r', '', '\r将敏感数据放置在POST数据包的DATA部分进行传输。\r'),
(85, '中间件程序版本信息泄漏', '\r系统没有设置统一的错误提示页面，在404、302、500等错误页面中将直接显示系统使用的中间件的版本信息。另外，在HTTP响应数据包的Header部分也可能泄漏中间件的版本信息。\r\r', '\r3\r', '\r攻击者在获得中间件版本信息后，可针对性的寻找当前版本中间件存在的安全漏洞，进而进行有针对性的攻击。\r', '', '\r定制统一的错误页面，当程序异常时显示统一的错误提示页面；删除/修改/隐藏HTTP Header中的中间件程序版本信息，避免信息泄漏。\rWAS中间件版本泄露安全漏洞，在控制台中的修改方法是： \r在管理控制台中，单击服务器 > 服务器类型，然后根据您要创建的链类型选择以下某个选项： \r应用程序服务器 > > server_name。在 Web 容器设置下，单击 Web 容器传输链 > WCInboundDefault> HTTP 入站通道 > 定制属性 > 新建。 \rname：RemoveServerHeader \rvalue：true\r'),
(86, '中间件程序版本过低', '\r在应用程序测试过程中，检测到所测试的应用系统的中间件程序版本过低。\r\r', '\r2\r', '\r中间件程序版本过低，低版本的程序存在多个高危漏洞，容易被攻击者恶意利用。\r', '', '\r升级中间件程序版本。\r'),
(87, '任意文件源码读取', '\r应用系统存在代码逻辑问题，攻击者可以读取应用系统中任意文件的源代码。\r\r', '\r1\r', '\r敏感信息的暴露会提供给攻击者更多的可用信息，引起更多被侵入的风险。\r', '', '\r修改应用系统源代码，限定应用程序可读文件的路径范围，禁止读取或访问其他数据。\r'),
(88, '会话cookie中缺少HttpOnly属性', '\r程序设置的会话 cookie未包含HttpOnly属性。\r\r', '\r3\r', '\r攻击者可结合XSS跨站等漏洞，通过往页面中插入恶意JS代码的方式获取用户的会话cookie，进而冒用用户身份发起进一步攻击。\r', '', '\r修改程序源代码，为用户会话cookie设置HttpOnly属性。\r'),
(89, '会话Cookie中缺少Secure属性', '\r程序设置的会话 cookie未包含secure属性，会话cookie将不被强制通过SSL加密协议传输，可以在不加密的HTTP协议中传输。\r\r', '\r3\r', '\r攻击者可以通过网络监听等方式获得用户与服务端交互的内容，进而获得未通过SSL加密发送的cookie内容。\r', '', '\r修改程序源代码，为用户会话cookie设置secure属性。\r'),
(90, '会话令牌不应写入URL', '\rjsessionid设计的初衷是代替不安全的cookie，所以jsessionid信息是保存在服务端和客户端的内存中的，这样攻击者就无法通过读取客户端cookie的方式获得用户的会话令牌来劫持用户会话。\r但是现在应用程序将用户的会话令牌jsessionid写入了URL，已经违背了jsessionid设计的初衷。\r\r', '\r2\r', '\r攻击者可以通过document.URI等方式获得当前的URL，进而获得用户的jsessionid会话令牌，最终发起用户会话劫持攻击。\r', '', '\r以cookie方式传递jsessionid，且应防止将jsessionid存入客户端硬盘。\r'),
(91, '会话信息明文写入cookie', '\r程序将会话信息明文写入了cookie。\r\r', '\r3\r', '\r攻击者可从cookie中读取用户的会话信息。\r', '', '\r使用session判断用户身份，禁止仅使用cookie判断用户身份。尽量避免使用cookie存储敏感信息，若不能避免，则写入cookie的内容必须加密。\r'),
(92, '会话标识未更新', '\r在应用程序测试过程中，检测到用户登录应用系统后，系统会给出一个名为jsessionid的会话标识，而这个名为jsessionid的会话标识在登陆前和登录后是没有改变的：\r\r', '\r1\r', '\r由于系统未更新会话标识，因此攻击者可利用窃取到的会话标识直接登录系统，进而绕过登录验证，伪装为合法用户。这些内容有利于攻击者开展进一步的攻击行为。\r', '', '\r修改应用程序源程序，始终生成新的会话，供用户成功认证时登录。防止攻击者操纵用户的会话标识。\r请勿接受用户浏览器登录时所提供的会话标识。\r'),
(93, '伪造邮件未拦截', '\r邮件服务器配置不严格，没有拦截攻击者通过伪造发件人身份技术发送的伪造邮件。\r\r', '\r1\r', '\r攻击者可以使用伪造的发件人身份发送任意邮件给用户，这可能导致挂马、钓鱼等风险。\r', '', '\r可启用邮件服务器的登录验证、检查邮件来源IP、检查邮件发送域、反向DNS查询等手段来避免接收伪造发件人的邮件。\r另外，也可以通过重要或敏感邮件线下或电话沟通等方式避免社会工程学等攻击。\r'),
(94, '关键字过滤不严', '\r系统只过滤了敏感词的大小写形式，但并没有过滤敏感词的URL编码形式。\r\r', '\r2\r', '\r系统只过滤了敏感词的大小写形式，但并没有过滤敏感词的URL编码形式，攻击者可通过URL编码形式绕过应用系统的过滤，进而实现更深层次的侵入。\r', '', '\r在过滤字符大小写的同时，过滤字符的URL编码形式，防止被绕过。\r'),
(95, '内部IP信息泄漏', '\r内部 IP 通常显现在 Web 应用程序/服务器所生成的错误消息中，或显现在 HTML/JavaScript 注释中。\r\r', '\r2\r', '\r对攻击者而言，泄露内部 IP 非常有价值，因为它显示了内部网络的 IP 地址方案。知道内部网络的 IP 地址方案，可以辅助攻击者策划出对内部网络进一步的攻击。\r', '', '\r关闭 Web 应用程序/服务器中有问题的详细错误消息。\r确保已安装相关的补丁。\r确保内部 IP 信息未留在 HTML/JavaScript 注释中。\r'),
(96, '前端可控的验证码生成机制', '\r应用系统的验证码生成机制存在逻辑缺陷，攻击者可以通过控制验证码请求数据包中的参数值来控制验证码的生成内容。\r\r', '\r1\r', '\r因为验证码生成内容在前端可控，那么验证码就失去了它应该具备的功能。\r', '', '\r修改验证码模块源代码，将验证码内容生成控制模块和验证码验证模块定义在后端。\r'),
(97, '前端可读的验证码生成机制', '\r应用系统的验证码生成机制存在逻辑缺陷，攻击者可以通过读取服务器返回的信息中获得验证码的生成内容。\r\r', '\r2\r', '\r程序在生成验证码后返回到了前端，攻击者可以直接读取前端的内容来获得验证码的内容，进而绕过验证码的限制实现CSRF或暴力猜解等目的。\r', '', '\r修改验证码模块源代码，不要将验证码的实际内容通过任何方式返回给客户端。\r'),
(98, '参数值溢出', '\r应用程序没有限定程序参数的最大范围，存在参数值溢出漏洞。攻击者可以发送过大的参数值到服务器，引起应用程序或数据库拒绝服务。将10000个A作为参数state的值发送到服务器，务器没有返回任何信息，说明已经拒绝服务\r稍后将state的值设置为正常值，发送到服务器，依然没有返回任何信息，说明确实已经拒绝服务。\r    \r', '\r1\r', '\r攻击者发送过大的参数值到服务器，将引起应用程序或数据库的拒绝服务。\r', '', '\r修改应用程序源代码，限定参数的最大值。\r'),
(99, '可被绕过的验证码验证机制', '\r系统的验证码验证机制不完善，攻击者可以发送任意次数的登录请求，程序都不会提示验证码错误。这说明程序根本没有验证验证码的正确性。\r\r', '\r2\r', '\r程序的登录模块没有验证验证码的正确性，导致验证码名存实亡，起不到保护作用。\r', '', '\r修改应用程序源代码，在登录模块中增加对验证码正确性的验证，并且要保证在验证用户名、密码或其他信息之前首先验证验证码的正确性。\r'),
(100, '启用了 Microsoft ASP.NET 调试', '\r系统启用了 Microsoft ASP.NET 调试，攻击者可以构造一个DEBUG调试请求发送到服务器。\r\r', '\r3\r', '\r系统配置不安全，启用了 Microsoft ASP.NET 调试，这可能导致信息泄漏。\r', '', '\r编辑web.config文件，将debug选项设置为关闭状态： <compilation debug="false"/>。\r'),
(101, '启用了 TRACE 和 TRACK HTTP 方法', '\r系统中间件的配置不当，启用了TRACE方法。\r\r', '\r3\r', '\r攻击者可在不安全的浏览器环境中，通过TRACE方法获取用户的会话标识。\r', '', '\r修改中间件配置，禁用TRACE方法。\r'),
(102, '启用了http put方法', '\r通过OPTIONS方法提交特定的请求，在响应中查看allow头信息，在allow头中发现delete、put等选项，delete方法是用来调试web服务器连接的http方式，支持该方式的服务器文件可能被非法删除；put方法用来向服务器提交文件，测试显示部分请求中这些方法是允许的。\r\r', '\r1\r', '\r恶意用户或攻击者一旦成功利用此漏洞，将可以通过调用put方法方法轻易上传webshell到服务器，可以通过调用delete方法轻易删除服务器中的文件。\r', '', '\r修改系统web服务器配置，禁止使用put、delete等方法。\r'),
(103, '启用了options http方法', '\r启用了不安全的http方法，Web服务器或应用程序服务器中间件是以不安全的方式配置 ，这些方法可能标识在服务器上启用了WebDAV，可能允许未授权的用户进行利用。此漏洞存在于IIS容器下，它扩展了HTTP协议，在GET/POST/HEAD等几个HTTP标准方法以外添加了一些新的方法，比如PUT/MOVE/COPY/DELETE方法，那么攻击者就可以通过PUT方法向服务器上传危险脚本。\r/\r', '\r3\r', '\r攻击者可以发送OPTIONS方法，从系统的响应中获得系统已启用的HTTP方法列表。\r', '', '\r如果服务器不需要支持WebDAV，请务必禁用此功能，或者禁止其不安全的HTTP请求方法。\r'),
(104, '启用了不安全的http方法', '\r通过OPTIONS方法提交特定的请求，在响应中查看allow头信息，在allow头中发现delete、put等选项，delete方法是用来调试web服务器连接的http方式，支持该方式的服务器文件可能被非法删除；put方法用来向服务器提交文件，测试显示部分请求中这些方法是允许的，截图如下：\r\r', '\r3\r', '\r恶意用户或攻击者一旦成功利用此漏洞，将可以通过调用Delete方法恶意删除服务器中的文件，可以调用Put方法上传恶意文件到服务器。\r', '', '\r修改系统web服务器配置，禁止使用delete、put等方法。\r'),
(105, '图形验证码可重复使用', '\r程序存在逻辑问题，没有限定图形验证码的使用次数，导致图形验证码可重复使用。\r第一次使用：\r\r重放数据包继续使用：\r\r', '\r2\r', '\r攻击者可利用此缺陷绕过图形验证码的防护进行暴力猜解攻击。\r', '', '\r在服务端限定并校验图形验证码的使用次数，每个图形验证码只能使用一次。\r'),
(106, '基于DOM的XSS跨站', '\r应用系统调用了本地DOM变量，且没有对本地DOM变量进行必要的安全处理。\r\r', '\r3\r', '\r攻击者可以通过构造URL注入JavaScript、VBScript、ActiveX、HTML或者Flash的手段，利用跨站脚本漏洞欺骗用户，收集Cookie等相关数据并冒充其他用户。通过精心构造的恶意代码，可以让访问者访问非法网站或下载恶意木马，如果再结合其他攻击手段（如社会工程学、提权等），甚至可以获取系统的管理权限。\r', '', '\r请分析并加强客户端 (JavaScript) 代码， 清理攻击者所能影响的输入源。\r例如：\rdocument.URL\rdocument.URLUnencoded\rdocument.location（及其许多属性）\rdocument.referrerwindow.location（及其许多属性）\r必须特别注意应用程序修改了 DOM 的情况。\r'),
(107, '基于DOM的任意URL跳转', '\r系统调用了document.location.href属性，但没有对document.location.href属性进行限定范围的处理，导致存在基于DOM的任意URL跳转漏洞。\r\r', '\r3\r', '\r攻击者可以随意定义将跳转的URL，这可能导致挂马攻击、钓鱼攻击等等，危害很大。\r', '', '\r调用document.location.href属性后进行范围限定处理，限定格式、范围等条件。\r'),
(108, '备份文件未删除', '\r应用系统的生产环境中存在备份文件。\r/\r可以直接下载并打开\r', '\r2\r', '\r攻击者可直接浏览或下载备份文件，获得应用系统的源代码、数据库执行方式等敏感信息。\r', '', '\r删除备份文件。\r'),
(109, '多登录入口', '\r应用程序存在多个登录入口。\r\r', '\r3\r', '\r攻击者可能绕过正常登录流程登录系统。\r', '', '\r删除受影响文件，保证程序只有一个登录入口。\r'),
(110, '安装文件未删除', '\r应用系统的生产环境中存在软件默认的安装说明文件。\r\r', '\r2\r', '\r攻击者可获得软件类型、版本等敏感信息，可有目标的查找当前软件类型和版本的漏洞发起针对性的攻击。\r', '', '\r删除无用的安装文件。\r'),
(111, '审计权限未分离', '\r应用系统管理员具备日志的访问权限，不符合安全审计要求。\r\r', '\r3\r', '\r攻击者一旦获得管理员帐号的权限，即可修改或删除审计日志，影响事后追溯。\r', '', '\r修改程序架构，使审计权限单独分离，除审计管理员外，其他任何账户都不应具备审计日志的访问权限。\r'),
(112, '客户端cookie引用', '\r系统引用了客户端cookie，这样攻击者就可以发送其本无权发送的cookie。\r\r', '\r3\r', '\r攻击者可通过发送其本无权发送的cookie来达到进一步的攻击目的，比如合法用户身份伪造。\r', '', '\r避免在客户端放置业务/安全逻辑。 \r查找并除去客户端不安全的 JavaScript 代码，该代码可能会对应用程序造成安全威胁。\r'),
(113, '密码不应返回前端', '\r程序将用户的密码返回了前端，很容易被攻击者截获。\r/\r', '\r2\r', '\r攻击者可以通过网络监听轻易获得程序返回给用户的密码。\r', '', '\r无论任何情况下，都禁止将用户的密码明文或密文返回前端。\r'),
(114, '应用程序弱口令', '\r在应用程序测试过程中，检测到所测试的应用系统存在可被猜解的弱口令。\r\r', '\r1\r', '\r应用程序配置不当，导致存在弱口令用户，这可能导致敏感信息泄漏，非法攻击者可利用弱口令冒用正常用户身份。\r', '', '\r为用户配置一个强壮的密码。\r'),
(115, '应用程序未容错', '\r应用程序未屏蔽执行过程中的错误信息，直接抛出了异常，造成敏感信息泄漏。\r/\r', '\r2\r', '\r攻击者可从程序的错误信息中获得程序开发框架名称及版本、SQL语句、SQL数据库表名、绝对路径等敏感信息。\r', '', '\r增加try catch等容错语句，所有异常必须捕获并处理，禁止直接抛出异常，禁止将异常信息输出到页面中。\r'),
(116, '应用程序未限制参数可选范围', '\r程序中有的参数/变量的正常值有一个范围，比如参数a的正常值的范围是数字1-10，那么如果攻击者将这个参数的值设置为11并提交给应用程序时，应用程序就会出错。\r\r', '\r2\r', '\r如果应用程序没有限制参数的可选范围，那程序将随时可被攻击者用来获取应用程序源代码、逻辑结构、绝对路径等敏感信息。\r', '', '\r为应用程序的参数限定一个用户可选的范围，在客户端和服务端同时对参数的合法性进行校验，避免出现不可控的参数值。\r'),
(117, '应用程序版本信息泄漏', '\r系统的具体类型和版本存在泄漏。\r\r', '\r2\r', '\r攻击者在获得应用程序的类型和版本后，可以寻找此版本应用程序的漏洞发起针对性的攻击。\r', '', '\r隐藏应用程序的版本信息。\r'),
(118, '应用系统管理后台地址泄漏', '\r在应用系统测试过程中，检测到所测试的应用系统存在管理后台地址泄漏风险。\r\r', '\r3\r', '\r应用系统管理后台地址太简单，导致攻击者可以轻易猜测到应用系统的管理后台地址，进而通过fuzzer等技术破解后台密码或通过其他技术攻击应用系统。\r', '', '\r1. 将管理后台的服务绑定到内网ip上，禁止开放在外网。\r2. 如果该管理后台必须提供给外网访问，则未登录页面不要显示过多内容，防止敏感信息泄漏，登录帐号需经过认证，且密码设置规则尽量复杂，增加验证码，以防止暴力破解。\r'),
(119, '弱用户名', '\r程序存在弱用户名，容易被攻击者用来进行暴力猜解攻击。\r存在的弱用户名有：\r\r', '\r2\r', '\r攻击者可利用弱用户名进行暴力猜解攻击。\r', '', '\r禁止使用弱用户名。\r'),
(120, '敏感信息泄漏', '\r在应用程序测试过程中，检测到所测试的应用系统存在敏感信息泄漏。攻击者可以通过暴露出来的敏感信息寻找利用方法进行进一步的侵入。\r\r', '\r2\r', '\r敏感信息的暴露会提供给攻击者更多的可用信息，引起更多被侵入的风险。\r', '', '\r删除受影响文件或者敏感数据，避免信息泄漏。\r'),
(121, '敏感数据GET传输', '\r应用系统的敏感数据是 GET方式传输的。\r\r', '2', 'GET方式传递的敏感数据更容易被截获，降低了攻击的门槛，攻击者通过简单的JavaScript脚本即可获得敏感数据的内容。', '', '\r使用POST方式传递敏感信息。\r'),
(122, '敏感数据明文传输', '\r系统使用了HTTPS访问模式，但是程序自身没有对传输的用户名和密码等敏感信息进行加密。\r\r', '\r2\r', '\r攻击者或者其他恶意用户通过网络窃听手段监听通讯协议，可以获取正常用户登陆过程，获取用户登陆密码或认证凭据，冒充合法用户登陆。\r', '', '\r建议在页面认证信息传输之前先对认证信息实现加密，不要使用base64/MD5/SHA1等过于简单的加密算法，建议使用AES或更高强度的算法实现加密。\r'),
(123, '无效的前端生成的图形验证码', '\r程序的图形验证码是在前端通过JS生成的，攻击者可以很容易的控制图形验证码的生成内容。\r\r', '\r1\r', '\r攻击者可以控制前端JS代码，可以很轻易的控制程序生成的图形验证码的内容，使图形验证码形同虚设，起不到相应的防护作用。\r', '', '\r禁止在前端生成图形验证码，必须在后端生成后以图片形式传递到前端。\r'),
(124, '无效的前端验证的图形验证码', '\r程序的图形验证码是在前端通过JS验证的，攻击者可以很容易的控制图形验证码的验证流程和结果。\r\r', '\r1\r', '\r攻击者可以控制前端JS代码，可以很轻易的控制图形验证码的验证流程和结果，使图形验证码形同虚设，起不到相应的防护作用。\r', '', '\r必须在服务端验证图形验证码的正确性。\r'),
(125, '无登录错误锁定功能', '\r程序无登录错误锁定功能，不能防御暴力猜解攻击。\r\r', '\r3\r', '\r攻击者可利用此缺陷发起暴力猜解攻击。\r', '', '\r为程序增加登录错误锁定功能，1分钟内连续错误5次建议锁定帐号5分钟。\r'),
(126, '更改密码时不需要输入原密码', '\r在应用程序测试过程中，发现在更改应用系统的用户密码时不需要输入原密码。\r\r', '\r3\r', '\r在修改账户口令时未进行二次身份验证，可能导致用户密码被非法更改。\r', '', '\r在修改账户口令时进行二次身份验证。\r'),
(127, '服务器路径泄露', '\r在应用程序测试过程中，发现在应用程序代码中存在绝对路径信息。\r/\r', '\r2\r', '\r可能会泄漏 Web 服务器安装的绝对路径，这可能会帮助攻击者开展进一步攻击和获取有关 Web 应用程序文件系统结构的信息。\r', '', '\r修改应用程序源代码，避免信息泄漏。\r'),
(128, '未限制用户可输入长度', '\r在应用程序测试过程中，在用户名密码处写入大量垃圾信息，发现应用系统未对用户可输入长度作出限制。\r\r', '\r3\r', '\r应用系统未对用户可输入长度作出限制，恶意攻击者可以通过提交大量垃圾信息造成应用程序/数据库溢出。\r', '', '\r限制用户的可输入数据的长度，禁止大量垃圾数据的提交。\r'),
(129, '未验证的URL跳转', '\r应用程序未限制可跳转的URL格式和范围，导致出现未验证的直接跳转。\r/\r', '\r2\r', '\r应用程序未限制可跳转的URL格式和范围，导致存在未验证的任意URL跳转漏洞。利用此漏洞，攻击者可以随意定义将跳转的URL，这可能导致挂马攻击、钓鱼攻击等等，危害很大。\r', '', '\r修改程序源代码，限定可跳转的URL的范围、格式等条件。\r'),
(130, '测试文件未删除', '\r开发者忘记了删除程序开发测试时使用的测试文件。\r\r', '\r3\r', '\r攻击者可能从这些页面中获得敏感信息以进行进一步的攻击。\r', '', '\r删除测试文件。\r'),
(131, '浏览器关闭后会话依然可用', '\r应用系统未对用户关闭浏览器后做事件处理，导致浏览器关闭后会话依然可用。\r\r', '\r3\r', '\r浏览器被关闭后会话依然可用，攻击者可利用此缺陷进行身份冒用。\r', '', '\r监测浏览器关闭事件，当发现浏览器被关闭时提示用户是否退出，或直接不提示结束会话。\r'),
(132, '版本过低不受厂商支持的Tomcat', '\r当前Tomcat版本过低，不再受厂商支持：\r\r', '\r1\r', '\r官方支持的Tomcat的最低版本为6.x，厂商不会再为过低版本的Tomcat提供安全更新补丁，这可能影响中间件的安全、稳定等多个方面。\r', '', '\r升级Tomcat到最新稳定版。\r'),
(133, '特殊字符过滤不严', '\r应用系统过滤了常见的XSS跨站攻击字符串，但其他特殊符号都没有过滤。\r已经被过滤的特殊字符有：\r\r未被过滤的特殊字符有：\r\r', '\r2\r', '\r应用系统只过滤了少量的特殊字符串，不能严密的防御XSS跨站攻击。\r', '', '\r对用户输入的数据进行全面安全检查或过滤，尤其注意检查是否包含HTML特殊字符。这些检查或过滤必须在服务器端完成，建议过滤的常见危险字符如下：\r;\r''\r"\r<>\r()\r,\r\\\rscript\rsvg\ralert\rconfirm\rprompt\ronload\ronmouseover\ronfocus\ronerror\rxss\r'),
(134, '用户敏感信息未模糊化', '\r应用系统在查询用户信息时，没有对敏感信息进行模糊化处理。\r\r', '\r1\r', '\r攻击者可通过此功能恶意获取用户的手机号码，真实姓名，身份证号等敏感信息。\r', '', '\r在查询用户信息时，对敏感信息进行模糊化处理。\r'),
(135, '登录信息直接写入cookie', '\r应用系统设计逻辑存在缺陷，将用户名、密码等登录信息直接写入cookie。\r\r', '\r1\r', '\r直接将登录信息写入cookie，这样攻击者只需要拿到cookie信息就得知了所有的敏感登录信息，冒充合法用户登陆。\r', '', '\r修改程序源代码，将会话敏感信息放在服务器，使用session代替cookie。\r'),
(136, '登录表单未设置禁止自动完成保护', '\r应用程序的登录模块没有设置禁止自动完成保护，当用户在上一次输入密码之后，浏览器会默认记住这些密码，并在将来再次输入密码的时候提示用户自动完成表单填充，这会泄漏用户的敏感信息。\r\r', '\r3\r', '\r对于没有设置禁止自动完成保护的登录表单来说，攻击可以很轻易的利用浏览器的自动填充功能，获取用户的敏感信息。\r', '', '\r为登录表单增加禁止自动完成保护，比如：\r<input type="text" name="username" autocomplete="off" />\r'),
(137, '登录错误消息凭证枚举', '\r应用程序在用户名/密码验证错误时会分别输出不同的错误信息，攻击者可能利用此缺陷进行暴力猜解攻击。\r用户名错误时，提示：\r/\r密码错误时，提示：\r/\r', '\r2\r', '\r应用程序在用户名/密码验证错误时会分别输出不同的错误信息，攻击者可能利用此缺陷进行暴力猜解攻击。\r', '', '\r不论用户名错误还是密码错误，都输出同样的错误信息。\r'),
(138, '目录遍历漏洞', '\r应用程序中间件配置不当，导致目录遍历。\r\r', '\r1\r', '\r由于中间件配置不当，导致服务器文件目录遍历，攻击者可以直接浏览服务器上存在的所有目录和文件。\r', '', '\r修改中间件配置，避免信息泄漏。\r'),
(139, '短信炸弹', '\r应用系统的登录模块短信密码生成机制存在逻辑缺陷，没有限定一段时间内可发送的短信数量，攻击者可以在知道对方用户名的情况下，通过fuzzer技术实现短信炸弹。\r\r', '\r1\r', '\r应用程序没有限定一段时间内给同一个用户可发送的短信数量，导致形成短信炸弹漏洞。\r', '', '\r修改短信发送模块源代码，限定一段时间内可发送的短信数量。\r'),
(140, '短信验证码可爆破', '\r应用系统没有限制短信验证码的错误尝试次数及频率，导致短信验证码可被爆破。\r\r', '\r3\r', '\r短信验证码为纯数字形式，且应用系统未限制短信验证码的错误尝试次数及频率，攻击者可通过fuzz技术爆破得到正确的验证码。\r', '', '\r修改应用系统源代码，限制时间段内短信验证码的错误尝试次数及频率，同时应提高短信验证码的多样性，比如将短信验证码设置为数字+字母的6位组合，提高短信验证码安全性。\r'),
(141, '管理后台不应该放在外网', '\r应用系统的管理后台是放在外网的，攻击者可以直接发起对管理后台的攻击。\r\r', '\r3\r', '\r相对前台的防护来说，后台的安全防护能力相对偏弱，若管理后台可以被直接通过外网访问，那么攻击者就可以直接发起对管理后台的攻击。\r', '', '\r如果不需要将管理后台放在外网，请将管理后台放入内网，外网只存放前端展示页面即可。\r如果确实需要将管理后台放在外网，请为管理后台设定访问策略或访问密码，比如只允许特定IP访问，或通过htpasswd等方式限定管理后台的访问条件。\r'),
(142, '系统无图形验证码功能', '\r系统没有图形验证码，无法防止暴力猜解攻击。\r\r', '\r3\r', '\r攻击者可通过暴力猜解攻击尝试登录系统，进而获取用户登陆密码或认证凭据，冒充合法用户登陆。\r', '', '\r为应用系统加上验证码功能。\r'),
(143, '系统无密码复杂度策略', '\r修改密码时，可成功将用户的密码修改为123456这样的弱口令。\r/\r密码修改为：1234qwer\r/\r', '\r2\r', '\r系统存在弱口令的风险增大，攻击者暴力猜解的成功率增大。\r', '', '\r为应用系统配置强制的密码策略，禁止设定不符合强度的密码。\r'),
(144, '系统无超时退出功能', '\r在应用程序测试过程中，检测到所测试的 Web 应用程序不具备超时自动退出功能。\r\r', '\r3\r', '\r不具备超时退出功能的应用系统很可能被攻击者利用进行身份冒用，进而进行进一步的利用。\r', '', '\r修改程序源代码，添加超时退出功能，比如登录后30分钟无动作则关闭会话。\r'),
(145, '系统超时时间过长', '\r系统超时时间超过10分钟。\r\r', '\r3\r', '\r超时时间过长的应用系统很可能被攻击者捕获到敏感信息，进而进行进一步的利用。\r', '', '\r修改程序源代码，减少超时时间。\r'),
(146, '网站漏洞未及时修补', '\r在网站被恶意攻击者侵入后，未及时检查并修复漏洞，导致网站存在恶意文件。\r\r', '\r1\r', '\r残留在服务器上的恶意文件会导致攻击者可以随时获得网站的控制权。\r', '', '\r删除恶意文件。\r'),
(147, '脆弱的加密方式', '\r应用系统对用户名和密码数据的加密算法为cmd5加密，通过简单的编码转换工具即可将密文解密。\r/\r/\r', '\r2\r', '\r应用系统对敏感信息加密处理强度不够，这可能导致用户信息泄漏等风险。\r', '', '\r修改应用系统源代码，使用更高强度的加密算法。\r'),
(148, '认证消息中间人欺骗', '\r系统认证过程的响应数据包过于简单，可以被篡改伪造之后再返回给前端。\r\r', '\r1\r', '\r攻击者可以篡改伪造响应数据包，欺骗前端使前端认为认证通过，进而绕过正常认证流程。\r', '', '\r在响应数据包中增加随机token，使每一次响应的数据包都不相同，避免响应数据包被篡改伪造。\r'),
(149, '说明文件未删除', '\r说明文件可能是开发文档、应用系统版本信息、备注信息等文件，这些文件不应该被放在WEB目录下。\r\r', '\r2\r', '\r攻击者可以轻易的通过残留在服务器上的说明文件对应用系统源代码、架构进行分析，进而找出程序弱点进行攻击。\r', '', '\r如果需要，请将说明文件移动到非WEB目录下。\r如果一定需要将说明文件放在WEB目录下，请对目录进行访问权限限制。\r如果不需要，请删除说明文件。\r'),
(150, '越权访问', '\r系统并没有判断用户登录状态或访问权限，导致越权访问。\r/\r/\r', '\r2\r', '\r系统并没有判断用户登录状态或访问权限，导致越权访问，攻击者通过越权访问可能获得更多有利于入侵的条件，进而进一步的入侵系统。\r', '', '\r在每个敏感页面判断用户登录状态和访问权限，避免越权访问。\r'),
(151, '邮件发件人可伪造', '\r邮件服务器配置不严格，启用了邮件中继功能，攻击者可以伪造发件人身份发送任意邮件。\r\r', '\r1\r', '\r攻击者可以通过telnet的方式连接至邮件服务器使用伪造的发件人身份发送任意邮件。\r', '', '\r如果用户需要使用邮件客户端收发邮件，可启用邮件服务器的登录验证、检查邮件来源IP、检查邮件发送域、反向DNS查询等手段避免邮件服务器被攻击者利用。\r如果用户不需要使用邮件客户端收发邮件，请禁用邮件服务器的邮件中继功能。\r另外，也可以通过禁用邮件服务器上的telnet服务、加强邮件服务器网络边界防护、重要或敏感邮件线下或电话沟通等方式避免社会工程学等攻击。\r'),
(152, '邮件炸弹', '\r应用系统未限定单位时间内可发送的邮件数量，存在邮件炸弹漏洞。\r\r', '\r2\r', '\r攻击者可利用此漏洞发起邮件炸弹攻击，消耗系统资源，影响用户感知。\r', '', '\r限定单位时间内可发送邮件的邮件数量。\r'),
(153, '链接注入', '\r程序过滤不严，虽然过滤了部分危险字符串和符号，但依然存在链接注入漏洞。\r\r', '\r1\r', '\r攻击者可插入恶意链接到页面中，并诱使用户点击。\r', '', '\r对用户输入的数据进行全面安全检查或过滤，尤其注意检查是否包含HTML特殊字符。这些检查或过滤必须在服务器端完成，建议过滤的常见危险字符如下：\r;\r''\r"\r<>\r()\r,\r\\\rscript\rsvg\ralert\rconfirm\rprompt\ronload\ronmouseover\ronfocus\ronerror\rxss\r'),
(154, '错误信息可定义', '\r应用系统没有限定错误信息的输出内容，导致攻击者可以自定义任意错误内容。\r\r', '\r2\r', '\r攻击者可以自定义任意错误内容，这可能导致XSS跨站、页面钓鱼、社会工程学等攻击。\r', '', '\r限定程序错误的输出信息，禁止攻击者自定义错误信息的内容。\r'),
(155, '长密码拒绝服务', '\r通过发送一个很长的密码（1.000.000字符）有可能导致拒绝服务器上的服务攻击。这可能导致对网站变得不可用或不响应。通常这个问题是由脆弱的密码散列实现造成的。当发送长密码，密码散列过程将导致CPU和内存耗尽。\r影响范围：\r/\r', '\r1\r', '\r攻击者可能会导致网站成为临时/无限期不可用或没有响应。\r', '', '\r密码散列实现必须固定，以限制接受密码的最大长度。\r'),
(159, 'name', 'miaoshu', '0', 'fenxi', 'url', 'jianyi'),
(10002, '未记录(低危模板)', '@@@@@@@@', '3', '@@@@@@@@', NULL, '@@@@@@@'),
(10001, '未记录(中危模板)', '@@@@@@@@', '2', '@@@@@@@@', NULL, '@@@@@@@'),
(10000, '未记录(高危模板)', '@@@@@@@@', '1', '@@@@@@@@', NULL, '@@@@@@@');

-- --------------------------------------------------------

--
-- 表的结构 `user`
--

CREATE TABLE IF NOT EXISTS `user` (
  `user` varchar(10) NOT NULL,
  `passwd` varchar(16) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- 转存表中的数据 `user`
--

INSERT INTO `user` (`user`, `passwd`) VALUES
('admin', 'admin'),
('admin2', '111111'),
('admin3', '111111');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
